"""create test_cases table

Revision ID: 36f9d93c952c
Revises: 348e926549f5
Create Date: 2025-05-01 17:52:50.705149

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "36f9d93c952c"
down_revision: Union[str, None] = "348e926549f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "test_cases",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("input", sa.String(), nullable=False),
        sa.Column("expected_output", sa.String(), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["contest_tasks.id"],
            name=op.f("fk_test_cases_task_id_contest_tasks"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_cases")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("test_cases")
    # ### end Alembic commands ###
