"""create contest_group_associations table

Revision ID: dd1b772ec87d
Revises: a7f3e2adb658
Create Date: 2025-05-01 12:06:35.315538

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dd1b772ec87d"
down_revision: Union[str, None] = "a7f3e2adb658"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contest_group_association",
        sa.Column("contest_id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column(
            "group_status",
            sa.Enum(
                "REGISTERED",
                "COMPLETED",
                "DISQUALIFIED",
                "REFUSED",
                name="team_status2",
            ),
            server_default="REGISTERED",
            nullable=False,
        ),
        sa.Column(
            "registration_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["contest_id"],
            ["contests.id"],
            name=op.f("fk_contest_group_association_contest_id_contests"),
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
            name=op.f("fk_contest_group_association_group_id_groups"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contest_group_association")),
        sa.UniqueConstraint("contest_id", "group_id", name="idx_unique_contest_group"),
    )
    op.create_index(
        "idx_contest_group_group_id",
        "contest_group_association",
        ["group_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_contest_group_group_id", table_name="contest_group_association")
    op.drop_table("contest_group_association")
    # ### end Alembic commands ###
