"""create hackathons table

Revision ID: 6979f3129083
Revises: 2b56ca4b60fd
Create Date: 2025-04-07 00:49:53.218068

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6979f3129083"
down_revision: Union[str, None] = "2b56ca4b60fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE IF EXISTS hackathonstatus")
    op.execute("DROP TYPE IF EXISTS hackathon_status")

    op.create_table(
        "hackathons",
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=True),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column(
            "hackathon_status",
            sa.Enum(
                "PLANNED",
                "ACTIVE",
                "COMPLETED",
                "CANCELED",
                name="hackathonstatus",
            ),
            server_default="PLANNED",
            nullable=False,
        ),
        sa.Column("max_participants", sa.Integer(), nullable=False),
        sa.Column(
            "current_participants",
            sa.Integer(),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_hackathon_status",
        "hackathons",
        ["hackathon_status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_hackathon_status", table_name="hackathons")
    op.drop_table("hackathons")
    # ### end Alembic commands ###
