"""create hackathon_user_associations table

Revision ID: 595ac515dec2
Revises: 2ecf7e9e0fbb
Create Date: 2025-04-07 00:56:49.047906

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "595ac515dec2"
down_revision: Union[str, None] = "2ecf7e9e0fbb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("DROP TYPE IF EXISTS participationstatus")
    op.execute("DROP TYPE IF EXISTS participation_status")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hackathon_user_association",
        sa.Column("hackathon_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "user_status",
            sa.Enum(
                "REGISTERED",
                "COMPLETED",
                "DISQUALIFIED",
                name="participationstatus",
            ),
            server_default="REGISTERED",
            nullable=False,
        ),
        sa.Column(
            "registration_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hackathon_id"],
            ["hackathons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "hackathon_id", "user_id", name="idx_unique_hackathon_user"
        ),
    )
    op.create_index(
        "idx_hackathon_user_user_id",
        "hackathon_user_association",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_hackathon_user_user_id", table_name="hackathon_user_association")
    op.drop_table("hackathon_user_association")
    # ### end Alembic commands ###
