"""Create task table

Revision ID: 93daafa85553
Revises: 7623e49530d1
Create Date: 2025-03-27 01:59:41.343421

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "93daafa85553"
down_revision: Union[str, None] = "7623e49530d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "task_type",
            sa.Enum(
                "CODING", "QUIZ", "DESIGN", "DATA_SCIENCE", "HARDWARE", name="task_type"
            ),
            nullable=False,
        ),
        sa.Column("hackathon_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hackathon_id"],
            ["hackathons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_task_hackathon", "tasks", ["hackathon_id"], unique=False)
    op.create_index(
        "idx_task_type", "tasks", ["task_type", "hackathon_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_task_type", table_name="tasks")
    op.drop_index("idx_task_hackathon", table_name="tasks")
    op.drop_table("tasks")
    # ### end Alembic commands ###
