"""add max_attempts and current_attempts to hackathon_tasks

Revision ID: 5b265eef9239
Revises: 36f9d93c952c  # ИСПРАВЛЕНО: было d42134de7ff5
Create Date: 2025-05-01 19:06:54.167191

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5b265eef9239"
down_revision: Union[str, None] = "36f9d93c952c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hackathon_tasks",
        sa.Column("max_attempts", sa.Integer(), server_default="5", nullable=False),
    )
    op.add_column(
        "hackathon_tasks",
        sa.Column("current_attempts", sa.Integer(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hackathon_tasks", "current_attempts")
    op.drop_column("hackathon_tasks", "max_attempts")
    # ### end Alembic commands ###