"""create contest_tasks table

Revision ID: 937214976cc5
Revises: 86d69ce50d90
Create Date: 2025-05-01 17:42:56.435330

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "937214976cc5"
down_revision: Union[str, None] = "86d69ce50d90"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contest_tasks",
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("contest_id", sa.Integer(), nullable=False),
        sa.Column("time_limit", sa.Integer(), nullable=False),
        sa.Column("memory_limit", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["contest_id"],
            ["contests.id"],
            name=op.f("fk_contest_tasks_contest_id_contests"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contest_tasks")),
    )
    op.create_index("idx_task_contest", "contest_tasks", ["contest_id"], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_task_contest", table_name="contest_tasks")
    op.drop_table("contest_tasks")
    # ### end Alembic commands ###
