"""Create hackathon-user association table

Revision ID: 7623e49530d1
Revises: c195ab56146e
Create Date: 2025-03-27 00:00:35.435949

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7623e49530d1"
down_revision: Union[str, None] = "c195ab56146e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hackathon_user_association",
        sa.Column("hackathon_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "user_status",
            sa.Enum(
                "REGISTERED",
                "COMPLETED",
                "DISQUALIFIED",
                name="participation_status",
            ),
            server_default="registered",
            nullable=False,
        ),
        sa.Column(
            "registration_date",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "user_role",
            sa.Enum(
                "PARTICIPANT",
                "CREATOR",
                name="user_role",
            ),
            server_default="participant",
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hackathon_id"],
            ["hackathons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "hackathon_id", "user_id", name="idx_unique_hackathon_user"
        ),
    )
    op.create_index(
        "idx_hackathon_user_user_id",
        "hackathon_user_association",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_hackathon_user_user_id", table_name="hackathon_user_association")
    op.drop_table("hackathon_user_association")
    # ### end Alembic commands ###
