"""create hackathons table

Revision ID: b4d9aada1529
Revises: 7c5404270e26
Create Date: 2025-04-07 20:32:52.080412

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b4d9aada1529"
down_revision: Union[str, None] = "7c5404270e26"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("DROP TYPE IF EXISTS hackathonstatus CASCADE")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hackathons",
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=900), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=True),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column(
            "hackathon_status",
            sa.Enum(
                "PLANNED",
                "ACTIVE",
                "COMPLETED",
                "CANCELED",
                name="hackathonstatus",
            ),
            server_default="PLANNED",
            nullable=False,
        ),
        sa.Column("max_participants", sa.Integer(), nullable=False),
        sa.Column(
            "current_participants",
            sa.Integer(),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
            name=op.f("fk_hackathons_creator_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hackathons")),
    )
    op.create_index(
        "idx_hackathon_status",
        "hackathons",
        ["hackathon_status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_hackathon_status", table_name="hackathons")
    op.drop_table("hackathons")
    # ### end Alembic commands ###
