"""create tasks table

Revision ID: 9a9390c58b2b
Revises: 900d6a621a5e
Create Date: 2025-04-07 20:38:28.275819

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9a9390c58b2b"
down_revision: Union[str, None] = "900d6a621a5e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("DROP TYPE IF EXISTS tasktype CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "task_type",
            sa.Enum(
                "CODING",
                "QUIZ",
                "DESIGN",
                "DATA_SCIENCE",
                "HARDWARE",
                name="tasktype",
            ),
            nullable=False,
        ),
        sa.Column("hackathon_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hackathon_id"],
            ["hackathons.id"],
            name=op.f("fk_tasks_hackathon_id_hackathons"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
    )
    op.create_index("idx_task_hackathon", "tasks", ["hackathon_id"], unique=False)
    op.create_index(
        "idx_task_type", "tasks", ["task_type", "hackathon_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_task_type", table_name="tasks")
    op.drop_index("idx_task_hackathon", table_name="tasks")
    op.drop_table("tasks")
    # ### end Alembic commands ###
