"""create hackathon_tasks table

Revision ID: 4e9f9f53389d
Revises: cdb31c1ff421
Create Date: 2025-05-01 12:18:34.039799

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4e9f9f53389d"
down_revision: Union[str, None] = "cdb31c1ff421"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hackathon_tasks",
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "task_type",
            sa.Enum(
                "CODING",
                "QUIZ",
                "DESIGN",
                "DATA_SCIENCE",
                "HARDWARE",
                name="tasktype",
            ),
            nullable=False,
        ),
        sa.Column("hackathon_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hackathon_id"],
            ["hackathons.id"],
            name=op.f("fk_hackathon_tasks_hackathon_id_hackathons"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hackathon_tasks")),
    )
    op.create_index(
        "idx_task_hackathon", "hackathon_tasks", ["hackathon_id"], unique=False
    )
    op.create_index(
        "idx_task_type",
        "hackathon_tasks",
        ["task_type", "hackathon_id"],
        unique=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_task_type", table_name="hackathon_tasks")
    op.drop_index("idx_task_hackathon", table_name="hackathon_tasks")
    op.drop_table("hackathon_tasks")
    # ### end Alembic commands ###
