"""create hackathon-user-associations table

Revision ID: 900d6a621a5e
Revises: 570717d6ba08
Create Date: 2025-04-07 20:37:20.063870

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "900d6a621a5e"
down_revision: Union[str, None] = "570717d6ba08"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("DROP TYPE IF EXISTS participationstatus CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hackathon_user_association",
        sa.Column("hackathon_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "user_status",
            sa.Enum(
                "REGISTERED",
                "COMPLETED",
                "DISQUALIFIED",
                name="participationstatus",
            ),
            server_default="REGISTERED",
            nullable=False,
        ),
        sa.Column(
            "registration_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hackathon_id"],
            ["hackathons.id"],
            name=op.f("fk_hackathon_user_association_hackathon_id_hackathons"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_hackathon_user_association_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hackathon_user_association")),
        sa.UniqueConstraint(
            "hackathon_id", "user_id", name="idx_unique_hackathon_user"
        ),
    )
    op.create_index(
        "idx_hackathon_user_user_id",
        "hackathon_user_association",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_hackathon_user_user_id", table_name="hackathon_user_association")
    op.drop_table("hackathon_user_association")
    # ### end Alembic commands ###
