services:
  pg:
    image: postgres
    environment:
      POSTGRES_DB: RiddleFlowDB
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./services/backend
    env_file:
      - ./services/backend/src/.env.docker
    ports:
      - 5000:5000
    volumes:
      - ./services/backend:/app
    depends_on:
      pg:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: >
      bash -c "uvicorn main:app --reload --host 0.0.0.0 --port 5000 && alembic upgrade head"

volumes:
  postgres_data:
  redis_data: