services:

  pg:
    image: postgres
    environment:
      POSTGRES_DB: RiddleFlowDB
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./services/backend
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@pg:5432/RiddleFlowDB
    ports:
      - 5000:5000
    volumes:
      - ./services/backend:/app
    depends_on:
      pg:
        condition: service_healthy
    command: >
      bash -c "uvicorn src.main:app --reload --host 0.0.0.0 --port 5000 && cd src/ && alembic upgrade head"


volumes:
  postgres_data:
